// Mocks generated by Mockito 5.4.4 from annotations
// in dart_libp2p_pubsub/test/gossipsub/gossipsub_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i19;
import 'dart:typed_data' as _i29;

import 'package:dart_libp2p/core/connmgr/conn_manager.dart' as _i6;
import 'package:dart_libp2p/core/crypto/keys.dart' as _i30;
import 'package:dart_libp2p/core/event/bus.dart' as _i7;
import 'package:dart_libp2p/core/host/host.dart' as _i9;
import 'package:dart_libp2p/core/multiaddr.dart' as _i18;
import 'package:dart_libp2p/core/network/conn.dart' as _i16;
import 'package:dart_libp2p/core/network/context.dart' as _i21;
import 'package:dart_libp2p/core/network/network.dart' as _i4;
import 'package:dart_libp2p/core/network/notifiee.dart' as _i17;
import 'package:dart_libp2p/core/network/rcmgr.dart' as _i15;
import 'package:dart_libp2p/core/network/stream.dart' as _i8;
import 'package:dart_libp2p/core/network/transport_conn.dart' as _i32;
import 'package:dart_libp2p/core/peer/addr_info.dart' as _i20;
import 'package:dart_libp2p/core/peer/peer_id.dart' as _i2;
import 'package:dart_libp2p/core/peerstore.dart' as _i3;
import 'package:dart_libp2p/core/protocol/switch.dart' as _i5;
import 'package:dart_libp2p/p2p/transport/connection_state.dart' as _i33;
import 'package:dart_libp2p_pubsub/src/core/comm.dart' as _i12;
import 'package:dart_libp2p_pubsub/src/core/message.dart' as _i28;
import 'package:dart_libp2p_pubsub/src/core/pubsub.dart' as _i22;
import 'package:dart_libp2p_pubsub/src/core/router.dart' as _i10;
import 'package:dart_libp2p_pubsub/src/core/sign.dart' as _i23;
import 'package:dart_libp2p_pubsub/src/core/subscription.dart' as _i13;
import 'package:dart_libp2p_pubsub/src/core/validation.dart' as _i27;
import 'package:dart_libp2p_pubsub/src/pb/rpc.pb.dart' as _i25;
import 'package:dart_libp2p_pubsub/src/pb/trace.pb.dart' as _i31;
import 'package:dart_libp2p_pubsub/src/tracing/tracer.dart' as _i11;
import 'package:dart_libp2p_pubsub/src/util/midgen.dart' as _i24;
import 'package:dcid/dcid.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i26;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePeerId_0 extends _i1.SmartFake implements _i2.PeerId {
  _FakePeerId_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePeerstore_1 extends _i1.SmartFake implements _i3.Peerstore {
  _FakePeerstore_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNetwork_2 extends _i1.SmartFake implements _i4.Network {
  _FakeNetwork_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProtocolSwitch_3 extends _i1.SmartFake
    implements _i5.ProtocolSwitch {
  _FakeProtocolSwitch_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnManager_4 extends _i1.SmartFake implements _i6.ConnManager {
  _FakeConnManager_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventBus_5 extends _i1.SmartFake implements _i7.EventBus {
  _FakeEventBus_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeP2PStream_6<T> extends _i1.SmartFake implements _i8.P2PStream<T> {
  _FakeP2PStream_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHost_7 extends _i1.SmartFake implements _i9.Host {
  _FakeHost_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouter_8 extends _i1.SmartFake implements _i10.Router {
  _FakeRouter_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventTracer_9 extends _i1.SmartFake implements _i11.EventTracer {
  _FakeEventTracer_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_10 extends _i1.SmartFake implements Duration {
  _FakeDuration_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePubSubProtocol_11 extends _i1.SmartFake
    implements _i12.PubSubProtocol {
  _FakePubSubProtocol_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubscription_12 extends _i1.SmartFake implements _i13.Subscription {
  _FakeSubscription_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCID_13 extends _i1.SmartFake implements _i14.CID {
  _FakeCID_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResourceManager_14 extends _i1.SmartFake
    implements _i15.ResourceManager {
  _FakeResourceManager_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConn_15 extends _i1.SmartFake implements _i16.Conn {
  _FakeConn_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotifiee_16 extends _i1.SmartFake implements _i17.Notifiee {
  _FakeNotifiee_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Host].
///
/// See the documentation for Mockito's code generation for more information.
class MockHost extends _i1.Mock implements _i9.Host {
  MockHost() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PeerId get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _FakePeerId_0(
          this,
          Invocation.getter(#id),
        ),
      ) as _i2.PeerId);

  @override
  _i3.Peerstore get peerStore => (super.noSuchMethod(
        Invocation.getter(#peerStore),
        returnValue: _FakePeerstore_1(
          this,
          Invocation.getter(#peerStore),
        ),
      ) as _i3.Peerstore);

  @override
  List<_i18.MultiAddr> get addrs => (super.noSuchMethod(
        Invocation.getter(#addrs),
        returnValue: <_i18.MultiAddr>[],
      ) as List<_i18.MultiAddr>);

  @override
  _i4.Network get network => (super.noSuchMethod(
        Invocation.getter(#network),
        returnValue: _FakeNetwork_2(
          this,
          Invocation.getter(#network),
        ),
      ) as _i4.Network);

  @override
  _i5.ProtocolSwitch get mux => (super.noSuchMethod(
        Invocation.getter(#mux),
        returnValue: _FakeProtocolSwitch_3(
          this,
          Invocation.getter(#mux),
        ),
      ) as _i5.ProtocolSwitch);

  @override
  _i6.ConnManager get connManager => (super.noSuchMethod(
        Invocation.getter(#connManager),
        returnValue: _FakeConnManager_4(
          this,
          Invocation.getter(#connManager),
        ),
      ) as _i6.ConnManager);

  @override
  _i7.EventBus get eventBus => (super.noSuchMethod(
        Invocation.getter(#eventBus),
        returnValue: _FakeEventBus_5(
          this,
          Invocation.getter(#eventBus),
        ),
      ) as _i7.EventBus);

  @override
  _i19.Future<void> connect(
    _i20.AddrInfo? pi, {
    _i21.Context? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [pi],
          {#context: context},
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  void setStreamHandler(
    String? pid,
    _i4.StreamHandler? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setStreamHandler,
          [
            pid,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setStreamHandlerMatch(
    String? pid,
    bool Function(String)? match,
    _i4.StreamHandler? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setStreamHandlerMatch,
          [
            pid,
            match,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeStreamHandler(String? pid) => super.noSuchMethod(
        Invocation.method(
          #removeStreamHandler,
          [pid],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<_i8.P2PStream<dynamic>> newStream(
    _i2.PeerId? p,
    List<String>? pids,
    _i21.Context? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #newStream,
          [
            p,
            pids,
            context,
          ],
        ),
        returnValue:
            _i19.Future<_i8.P2PStream<dynamic>>.value(_FakeP2PStream_6<dynamic>(
          this,
          Invocation.method(
            #newStream,
            [
              p,
              pids,
              context,
            ],
          ),
        )),
      ) as _i19.Future<_i8.P2PStream<dynamic>>);

  @override
  _i19.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);
}

/// A class which mocks [PubSub].
///
/// See the documentation for Mockito's code generation for more information.
class MockPubSub extends _i1.Mock implements _i22.PubSub {
  MockPubSub() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Host get host => (super.noSuchMethod(
        Invocation.getter(#host),
        returnValue: _FakeHost_7(
          this,
          Invocation.getter(#host),
        ),
      ) as _i9.Host);

  @override
  _i10.Router get router => (super.noSuchMethod(
        Invocation.getter(#router),
        returnValue: _FakeRouter_8(
          this,
          Invocation.getter(#router),
        ),
      ) as _i10.Router);

  @override
  _i11.EventTracer get tracer => (super.noSuchMethod(
        Invocation.getter(#tracer),
        returnValue: _FakeEventTracer_9(
          this,
          Invocation.getter(#tracer),
        ),
      ) as _i11.EventTracer);

  @override
  Duration get validatorTimeout => (super.noSuchMethod(
        Invocation.getter(#validatorTimeout),
        returnValue: _FakeDuration_10(
          this,
          Invocation.getter(#validatorTimeout),
        ),
      ) as Duration);

  @override
  int get validateThrottle => (super.noSuchMethod(
        Invocation.getter(#validateThrottle),
        returnValue: 0,
      ) as int);

  @override
  int get maxMessageSize => (super.noSuchMethod(
        Invocation.getter(#maxMessageSize),
        returnValue: 0,
      ) as int);

  @override
  _i23.MessageSignaturePolicy get signaturePolicy => (super.noSuchMethod(
        Invocation.getter(#signaturePolicy),
        returnValue: _i23.MessageSignaturePolicy.strictSign,
      ) as _i23.MessageSignaturePolicy);

  @override
  bool get noAuthor => (super.noSuchMethod(
        Invocation.getter(#noAuthor),
        returnValue: false,
      ) as bool);

  @override
  _i12.PubSubProtocol get comms => (super.noSuchMethod(
        Invocation.getter(#comms),
        returnValue: _FakePubSubProtocol_11(
          this,
          Invocation.getter(#comms),
        ),
      ) as _i12.PubSubProtocol);

  @override
  _i24.MessageIdFn get messageIdFn => (super.noSuchMethod(
        Invocation.getter(#messageIdFn),
        returnValue: (_i25.Message message) => _i26.dummyValue<String>(
          this,
          Invocation.getter(#messageIdFn),
        ),
      ) as _i24.MessageIdFn);

  @override
  _i13.Subscription subscribe(String? topic) => (super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [topic],
        ),
        returnValue: _FakeSubscription_12(
          this,
          Invocation.method(
            #subscribe,
            [topic],
          ),
        ),
      ) as _i13.Subscription);

  @override
  void announceSubscriptionsTo(_i2.PeerId? peerId) => super.noSuchMethod(
        Invocation.method(
          #announceSubscriptionsTo,
          [peerId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<void> unsubscribe(String? topic) => (super.noSuchMethod(
        Invocation.method(
          #unsubscribe,
          [topic],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  List<String> getTopics() => (super.noSuchMethod(
        Invocation.method(
          #getTopics,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  void registerMessageValidator(_i22.MessageValidator? validator) =>
      super.noSuchMethod(
        Invocation.method(
          #registerMessageValidator,
          [validator],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerTopicValidator(
    String? topic,
    _i22.TopicValidator? validator, {
    Duration? timeout,
    int? concurrency,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerTopicValidator,
          [
            topic,
            validator,
          ],
          {
            #timeout: timeout,
            #concurrency: concurrency,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool unregisterTopicValidator(String? topic) => (super.noSuchMethod(
        Invocation.method(
          #unregisterTopicValidator,
          [topic],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i19.Future<_i27.ValidationResult> validateMessage(
    _i28.PubSubMessage? message, {
    bool Function()? markSeen,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateMessage,
          [message],
          {#markSeen: markSeen},
        ),
        returnValue: _i19.Future<_i27.ValidationResult>.value(
            _i27.ValidationResult.accept),
      ) as _i19.Future<_i27.ValidationResult>);

  @override
  _i19.Future<void> publish(
    String? topic,
    _i29.Uint8List? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #publish,
          [
            topic,
            data,
          ],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  void deliverMessage(_i28.PubSubMessage? message) => super.noSuchMethod(
        Invocation.method(
          #deliverMessage,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deliverReceivedMessage(_i28.PubSubMessage? message) =>
      super.noSuchMethod(
        Invocation.method(
          #deliverReceivedMessage,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removePeer(_i2.PeerId? peerId) => super.noSuchMethod(
        Invocation.method(
          #removePeer,
          [peerId],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PeerId].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeerId extends _i1.Mock implements _i2.PeerId {
  MockPeerId() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.CID toCid() => (super.noSuchMethod(
        Invocation.method(
          #toCid,
          [],
        ),
        returnValue: _FakeCID_13(
          this,
          Invocation.method(
            #toCid,
            [],
          ),
        ),
      ) as _i14.CID);

  @override
  _i29.Uint8List toBytes() => (super.noSuchMethod(
        Invocation.method(
          #toBytes,
          [],
        ),
        returnValue: _i29.Uint8List(0),
      ) as _i29.Uint8List);

  @override
  String toCIDString() => (super.noSuchMethod(
        Invocation.method(
          #toCIDString,
          [],
        ),
        returnValue: _i26.dummyValue<String>(
          this,
          Invocation.method(
            #toCIDString,
            [],
          ),
        ),
      ) as String);

  @override
  String toBase58() => (super.noSuchMethod(
        Invocation.method(
          #toBase58,
          [],
        ),
        returnValue: _i26.dummyValue<String>(
          this,
          Invocation.method(
            #toBase58,
            [],
          ),
        ),
      ) as String);

  @override
  String shortString() => (super.noSuchMethod(
        Invocation.method(
          #shortString,
          [],
        ),
        returnValue: _i26.dummyValue<String>(
          this,
          Invocation.method(
            #shortString,
            [],
          ),
        ),
      ) as String);

  @override
  Map<String, dynamic> loggable() => (super.noSuchMethod(
        Invocation.method(
          #loggable,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool matchesPublicKey(_i30.PublicKey? publicKey) => (super.noSuchMethod(
        Invocation.method(
          #matchesPublicKey,
          [publicKey],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool matchesPrivateKey(_i30.PrivateKey? privateKey) => (super.noSuchMethod(
        Invocation.method(
          #matchesPrivateKey,
          [privateKey],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i19.Future<_i30.PublicKey?> extractPublicKey() => (super.noSuchMethod(
        Invocation.method(
          #extractPublicKey,
          [],
        ),
        returnValue: _i19.Future<_i30.PublicKey?>.value(),
      ) as _i19.Future<_i30.PublicKey?>);

  @override
  bool isValid() => (super.noSuchMethod(
        Invocation.method(
          #isValid,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [EventTracer].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventTracer extends _i1.Mock implements _i11.EventTracer {
  MockEventTracer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void trace(_i31.TraceEvent? event) => super.noSuchMethod(
        Invocation.method(
          #trace,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<void> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);
}

/// A class which mocks [PubSubProtocol].
///
/// See the documentation for Mockito's code generation for more information.
class MockPubSubProtocol extends _i1.Mock implements _i12.PubSubProtocol {
  MockPubSubProtocol() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onNewInboundPeer(
          void Function(
            _i2.PeerId,
            String,
          )? _onNewInboundPeer) =>
      super.noSuchMethod(
        Invocation.setter(
          #onNewInboundPeer,
          _onNewInboundPeer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onPeerDead(void Function(_i2.PeerId)? _onPeerDead) => super.noSuchMethod(
        Invocation.setter(
          #onPeerDead,
          _onPeerDead,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> get protocols => (super.noSuchMethod(
        Invocation.getter(#protocols),
        returnValue: <String>[],
      ) as List<String>);

  @override
  Duration get streamCloseTimeout => (super.noSuchMethod(
        Invocation.getter(#streamCloseTimeout),
        returnValue: _FakeDuration_10(
          this,
          Invocation.getter(#streamCloseTimeout),
        ),
      ) as Duration);

  @override
  int get maxMessageSize => (super.noSuchMethod(
        Invocation.getter(#maxMessageSize),
        returnValue: 0,
      ) as int);

  @override
  void start() => super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String? protocolOf(_i2.PeerId? peerId) =>
      (super.noSuchMethod(Invocation.method(
        #protocolOf,
        [peerId],
      )) as String?);

  @override
  _i19.Future<void> sendRpc(
    _i2.PeerId? peerId,
    _i25.RPC? rpc,
    String? protocolId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendRpc,
          [
            peerId,
            rpc,
            protocolId,
          ],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> closePeerStream(_i2.PeerId? peerId) => (super.noSuchMethod(
        Invocation.method(
          #closePeerStream,
          [peerId],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);
}

/// A class which mocks [Network].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetwork extends _i1.Mock implements _i4.Network {
  MockNetwork() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i18.MultiAddr> get listenAddresses => (super.noSuchMethod(
        Invocation.getter(#listenAddresses),
        returnValue: <_i18.MultiAddr>[],
      ) as List<_i18.MultiAddr>);

  @override
  _i19.Future<List<_i18.MultiAddr>> get interfaceListenAddresses =>
      (super.noSuchMethod(
        Invocation.getter(#interfaceListenAddresses),
        returnValue:
            _i19.Future<List<_i18.MultiAddr>>.value(<_i18.MultiAddr>[]),
      ) as _i19.Future<List<_i18.MultiAddr>>);

  @override
  _i15.ResourceManager get resourceManager => (super.noSuchMethod(
        Invocation.getter(#resourceManager),
        returnValue: _FakeResourceManager_14(
          this,
          Invocation.getter(#resourceManager),
        ),
      ) as _i15.ResourceManager);

  @override
  _i3.Peerstore get peerstore => (super.noSuchMethod(
        Invocation.getter(#peerstore),
        returnValue: _FakePeerstore_1(
          this,
          Invocation.getter(#peerstore),
        ),
      ) as _i3.Peerstore);

  @override
  _i2.PeerId get localPeer => (super.noSuchMethod(
        Invocation.getter(#localPeer),
        returnValue: _FakePeerId_0(
          this,
          Invocation.getter(#localPeer),
        ),
      ) as _i2.PeerId);

  @override
  List<_i2.PeerId> get peers => (super.noSuchMethod(
        Invocation.getter(#peers),
        returnValue: <_i2.PeerId>[],
      ) as List<_i2.PeerId>);

  @override
  List<_i16.Conn> get conns => (super.noSuchMethod(
        Invocation.getter(#conns),
        returnValue: <_i16.Conn>[],
      ) as List<_i16.Conn>);

  @override
  _i19.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  void setStreamHandler(
    String? protocol,
    _i19.Future<void> Function(
      dynamic,
      _i2.PeerId,
    )? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setStreamHandler,
          [
            protocol,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<_i8.P2PStream<dynamic>> newStream(
    _i21.Context? context,
    _i2.PeerId? peerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #newStream,
          [
            context,
            peerId,
          ],
        ),
        returnValue:
            _i19.Future<_i8.P2PStream<dynamic>>.value(_FakeP2PStream_6<dynamic>(
          this,
          Invocation.method(
            #newStream,
            [
              context,
              peerId,
            ],
          ),
        )),
      ) as _i19.Future<_i8.P2PStream<dynamic>>);

  @override
  _i19.Future<void> listen(List<_i18.MultiAddr>? addrs) => (super.noSuchMethod(
        Invocation.method(
          #listen,
          [addrs],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<_i16.Conn> dialPeer(
    _i21.Context? context,
    _i2.PeerId? peerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #dialPeer,
          [
            context,
            peerId,
          ],
        ),
        returnValue: _i19.Future<_i16.Conn>.value(_FakeConn_15(
          this,
          Invocation.method(
            #dialPeer,
            [
              context,
              peerId,
            ],
          ),
        )),
      ) as _i19.Future<_i16.Conn>);

  @override
  _i19.Future<void> closePeer(_i2.PeerId? peerId) => (super.noSuchMethod(
        Invocation.method(
          #closePeer,
          [peerId],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i4.Connectedness connectedness(_i2.PeerId? peerId) => (super.noSuchMethod(
        Invocation.method(
          #connectedness,
          [peerId],
        ),
        returnValue: _i4.Connectedness.notConnected,
      ) as _i4.Connectedness);

  @override
  List<_i16.Conn> connsToPeer(_i2.PeerId? peerId) => (super.noSuchMethod(
        Invocation.method(
          #connsToPeer,
          [peerId],
        ),
        returnValue: <_i16.Conn>[],
      ) as List<_i16.Conn>);

  @override
  void notify(_i17.Notifiee? notifiee) => super.noSuchMethod(
        Invocation.method(
          #notify,
          [notifiee],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopNotify(_i17.Notifiee? notifiee) => super.noSuchMethod(
        Invocation.method(
          #stopNotify,
          [notifiee],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool canDial(
    _i2.PeerId? peerId,
    _i18.MultiAddr? addr,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #canDial,
          [
            peerId,
            addr,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  void removeListenAddress(_i18.MultiAddr? addr) => super.noSuchMethod(
        Invocation.method(
          #removeListenAddress,
          [addr],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ConnManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnManager extends _i1.Mock implements _i6.ConnManager {
  MockConnManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.Notifiee get notifiee => (super.noSuchMethod(
        Invocation.getter(#notifiee),
        returnValue: _FakeNotifiee_16(
          this,
          Invocation.getter(#notifiee),
        ),
      ) as _i17.Notifiee);

  @override
  void tagPeer(
    _i2.PeerId? peerId,
    String? tag,
    int? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #tagPeer,
          [
            peerId,
            tag,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void untagPeer(
    _i2.PeerId? peerId,
    String? tag,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #untagPeer,
          [
            peerId,
            tag,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void upsertTag(
    _i2.PeerId? peerId,
    String? tag,
    int Function(int)? upsert,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #upsertTag,
          [
            peerId,
            tag,
            upsert,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.TagInfo? getTagInfo(_i2.PeerId? peerId) =>
      (super.noSuchMethod(Invocation.method(
        #getTagInfo,
        [peerId],
      )) as _i6.TagInfo?);

  @override
  _i19.Future<void> trimOpenConns() => (super.noSuchMethod(
        Invocation.method(
          #trimOpenConns,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  void protect(
    _i2.PeerId? peerId,
    String? tag,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #protect,
          [
            peerId,
            tag,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool unprotect(
    _i2.PeerId? peerId,
    String? tag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unprotect,
          [
            peerId,
            tag,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isProtected(
    _i2.PeerId? peerId,
    String? tag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isProtected,
          [
            peerId,
            tag,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  String? checkLimit(_i6.GetConnLimiter? limiter) =>
      (super.noSuchMethod(Invocation.method(
        #checkLimit,
        [limiter],
      )) as String?);

  @override
  _i19.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  void registerConnection(_i32.TransportConn? conn) => super.noSuchMethod(
        Invocation.method(
          #registerConnection,
          [conn],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateState(
    _i32.TransportConn? conn,
    _i33.ConnectionState? state, {
    required Object? error,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateState,
          [
            conn,
            state,
          ],
          {#error: error},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i33.ConnectionState? getState(_i32.TransportConn? conn) =>
      (super.noSuchMethod(Invocation.method(
        #getState,
        [conn],
      )) as _i33.ConnectionState?);

  @override
  void recordActivity(_i32.TransportConn? tcpConnection) => super.noSuchMethod(
        Invocation.method(
          #recordActivity,
          [tcpConnection],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Stream<_i33.ConnectionStateChange>? getStateStream(
          _i32.TransportConn? conn) =>
      (super.noSuchMethod(Invocation.method(
        #getStateStream,
        [conn],
      )) as _i19.Stream<_i33.ConnectionStateChange>?);

  @override
  _i19.Future<void> closeConnection(_i32.TransportConn? conn) =>
      (super.noSuchMethod(
        Invocation.method(
          #closeConnection,
          [conn],
        ),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);
}
