// Mocks generated by Mockito 5.4.4 from annotations
// in dart_libp2p_pubsub/test/gossipsub/persistent_streams_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;
import 'dart:typed_data' as _i17;

import 'package:dart_libp2p/core/connmgr/conn_manager.dart' as _i6;
import 'package:dart_libp2p/core/crypto/keys.dart' as _i19;
import 'package:dart_libp2p/core/event/bus.dart' as _i7;
import 'package:dart_libp2p/core/host/host.dart' as _i12;
import 'package:dart_libp2p/core/multiaddr.dart' as _i13;
import 'package:dart_libp2p/core/network/conn.dart' as _i9;
import 'package:dart_libp2p/core/network/context.dart' as _i16;
import 'package:dart_libp2p/core/network/network.dart' as _i4;
import 'package:dart_libp2p/core/network/rcmgr.dart' as _i10;
import 'package:dart_libp2p/core/network/stream.dart' as _i8;
import 'package:dart_libp2p/core/peer/addr_info.dart' as _i15;
import 'package:dart_libp2p/core/peer/peer_id.dart' as _i2;
import 'package:dart_libp2p/core/peerstore.dart' as _i3;
import 'package:dart_libp2p/core/protocol/switch.dart' as _i5;
import 'package:dcid/dcid.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePeerId_0 extends _i1.SmartFake implements _i2.PeerId {
  _FakePeerId_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePeerstore_1 extends _i1.SmartFake implements _i3.Peerstore {
  _FakePeerstore_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNetwork_2 extends _i1.SmartFake implements _i4.Network {
  _FakeNetwork_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProtocolSwitch_3 extends _i1.SmartFake
    implements _i5.ProtocolSwitch {
  _FakeProtocolSwitch_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnManager_4 extends _i1.SmartFake implements _i6.ConnManager {
  _FakeConnManager_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventBus_5 extends _i1.SmartFake implements _i7.EventBus {
  _FakeEventBus_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeP2PStream_6<T> extends _i1.SmartFake implements _i8.P2PStream<T> {
  _FakeP2PStream_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConn_7 extends _i1.SmartFake implements _i9.Conn {
  _FakeConn_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamStats_8 extends _i1.SmartFake implements _i8.StreamStats {
  _FakeStreamStats_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamManagementScope_9 extends _i1.SmartFake
    implements _i10.StreamManagementScope {
  _FakeStreamManagementScope_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCID_10 extends _i1.SmartFake implements _i11.CID {
  _FakeCID_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Host].
///
/// See the documentation for Mockito's code generation for more information.
class MockHost extends _i1.Mock implements _i12.Host {
  MockHost() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PeerId get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _FakePeerId_0(
          this,
          Invocation.getter(#id),
        ),
      ) as _i2.PeerId);

  @override
  _i3.Peerstore get peerStore => (super.noSuchMethod(
        Invocation.getter(#peerStore),
        returnValue: _FakePeerstore_1(
          this,
          Invocation.getter(#peerStore),
        ),
      ) as _i3.Peerstore);

  @override
  List<_i13.MultiAddr> get addrs => (super.noSuchMethod(
        Invocation.getter(#addrs),
        returnValue: <_i13.MultiAddr>[],
      ) as List<_i13.MultiAddr>);

  @override
  _i4.Network get network => (super.noSuchMethod(
        Invocation.getter(#network),
        returnValue: _FakeNetwork_2(
          this,
          Invocation.getter(#network),
        ),
      ) as _i4.Network);

  @override
  _i5.ProtocolSwitch get mux => (super.noSuchMethod(
        Invocation.getter(#mux),
        returnValue: _FakeProtocolSwitch_3(
          this,
          Invocation.getter(#mux),
        ),
      ) as _i5.ProtocolSwitch);

  @override
  _i6.ConnManager get connManager => (super.noSuchMethod(
        Invocation.getter(#connManager),
        returnValue: _FakeConnManager_4(
          this,
          Invocation.getter(#connManager),
        ),
      ) as _i6.ConnManager);

  @override
  _i7.EventBus get eventBus => (super.noSuchMethod(
        Invocation.getter(#eventBus),
        returnValue: _FakeEventBus_5(
          this,
          Invocation.getter(#eventBus),
        ),
      ) as _i7.EventBus);

  @override
  _i14.Future<void> connect(
    _i15.AddrInfo? pi, {
    _i16.Context? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [pi],
          {#context: context},
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  void setStreamHandler(
    String? pid,
    _i4.StreamHandler? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setStreamHandler,
          [
            pid,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setStreamHandlerMatch(
    String? pid,
    bool Function(String)? match,
    _i4.StreamHandler? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setStreamHandlerMatch,
          [
            pid,
            match,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeStreamHandler(String? pid) => super.noSuchMethod(
        Invocation.method(
          #removeStreamHandler,
          [pid],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<_i8.P2PStream<dynamic>> newStream(
    _i2.PeerId? p,
    List<String>? pids,
    _i16.Context? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #newStream,
          [
            p,
            pids,
            context,
          ],
        ),
        returnValue:
            _i14.Future<_i8.P2PStream<dynamic>>.value(_FakeP2PStream_6<dynamic>(
          this,
          Invocation.method(
            #newStream,
            [
              p,
              pids,
              context,
            ],
          ),
        )),
      ) as _i14.Future<_i8.P2PStream<dynamic>>);

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);
}

/// A class which mocks [P2PStream].
///
/// See the documentation for Mockito's code generation for more information.
class MockP2PStream<T> extends _i1.Mock implements _i8.P2PStream<T> {
  MockP2PStream() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Conn get conn => (super.noSuchMethod(
        Invocation.getter(#conn),
        returnValue: _FakeConn_7(
          this,
          Invocation.getter(#conn),
        ),
      ) as _i9.Conn);

  @override
  _i8.P2PStream<_i17.Uint8List> get incoming => (super.noSuchMethod(
        Invocation.getter(#incoming),
        returnValue: _FakeP2PStream_6<_i17.Uint8List>(
          this,
          Invocation.getter(#incoming),
        ),
      ) as _i8.P2PStream<_i17.Uint8List>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  String id() => (super.noSuchMethod(
        Invocation.method(
          #id,
          [],
        ),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #id,
            [],
          ),
        ),
      ) as String);

  @override
  String protocol() => (super.noSuchMethod(
        Invocation.method(
          #protocol,
          [],
        ),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #protocol,
            [],
          ),
        ),
      ) as String);

  @override
  _i14.Future<void> setProtocol(String? id) => (super.noSuchMethod(
        Invocation.method(
          #setProtocol,
          [id],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i8.StreamStats stat() => (super.noSuchMethod(
        Invocation.method(
          #stat,
          [],
        ),
        returnValue: _FakeStreamStats_8(
          this,
          Invocation.method(
            #stat,
            [],
          ),
        ),
      ) as _i8.StreamStats);

  @override
  _i10.StreamManagementScope scope() => (super.noSuchMethod(
        Invocation.method(
          #scope,
          [],
        ),
        returnValue: _FakeStreamManagementScope_9(
          this,
          Invocation.method(
            #scope,
            [],
          ),
        ),
      ) as _i10.StreamManagementScope);

  @override
  _i14.Future<_i17.Uint8List> read([int? maxLength]) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [maxLength],
        ),
        returnValue: _i14.Future<_i17.Uint8List>.value(_i17.Uint8List(0)),
      ) as _i14.Future<_i17.Uint8List>);

  @override
  _i14.Future<void> write(_i17.Uint8List? data) => (super.noSuchMethod(
        Invocation.method(
          #write,
          [data],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> closeWrite() => (super.noSuchMethod(
        Invocation.method(
          #closeWrite,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> closeRead() => (super.noSuchMethod(
        Invocation.method(
          #closeRead,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> setDeadline(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setDeadline,
          [time],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> setReadDeadline(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setReadDeadline,
          [time],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> setWriteDeadline(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setWriteDeadline,
          [time],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);
}

/// A class which mocks [PeerId].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeerId extends _i1.Mock implements _i2.PeerId {
  MockPeerId() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.CID toCid() => (super.noSuchMethod(
        Invocation.method(
          #toCid,
          [],
        ),
        returnValue: _FakeCID_10(
          this,
          Invocation.method(
            #toCid,
            [],
          ),
        ),
      ) as _i11.CID);

  @override
  _i17.Uint8List toBytes() => (super.noSuchMethod(
        Invocation.method(
          #toBytes,
          [],
        ),
        returnValue: _i17.Uint8List(0),
      ) as _i17.Uint8List);

  @override
  String toCIDString() => (super.noSuchMethod(
        Invocation.method(
          #toCIDString,
          [],
        ),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #toCIDString,
            [],
          ),
        ),
      ) as String);

  @override
  String toBase58() => (super.noSuchMethod(
        Invocation.method(
          #toBase58,
          [],
        ),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #toBase58,
            [],
          ),
        ),
      ) as String);

  @override
  String shortString() => (super.noSuchMethod(
        Invocation.method(
          #shortString,
          [],
        ),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #shortString,
            [],
          ),
        ),
      ) as String);

  @override
  Map<String, dynamic> loggable() => (super.noSuchMethod(
        Invocation.method(
          #loggable,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool matchesPublicKey(_i19.PublicKey? publicKey) => (super.noSuchMethod(
        Invocation.method(
          #matchesPublicKey,
          [publicKey],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool matchesPrivateKey(_i19.PrivateKey? privateKey) => (super.noSuchMethod(
        Invocation.method(
          #matchesPrivateKey,
          [privateKey],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i14.Future<_i19.PublicKey?> extractPublicKey() => (super.noSuchMethod(
        Invocation.method(
          #extractPublicKey,
          [],
        ),
        returnValue: _i14.Future<_i19.PublicKey?>.value(),
      ) as _i14.Future<_i19.PublicKey?>);

  @override
  bool isValid() => (super.noSuchMethod(
        Invocation.method(
          #isValid,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
